from enum import StrEnum


class ProjectStatus(StrEnum):
    ACTIVE = "ACTIVE"
    CLOSED = "CLOSED"


class RequirementState(StrEnum):
    OPEN = "OPEN"
    PARTIAL = "PARTIAL"
    SATISFIED = "SATISFIED"
    REVIEW = "REVIEW"


class CorrespondenceProcessingState(StrEnum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    RETRYABLE_FAILURE = "RETRYABLE_FAILURE"
    TERMINAL_FAILURE = "TERMINAL_FAILURE"


class AttachmentProcessingState(StrEnum):
    PENDING = "PENDING"
    EXTRACTED = "EXTRACTED"
    FALLBACK_REQUIRED = "FALLBACK_REQUIRED"
    UNSUPPORTED = "UNSUPPORTED"
    FAILED = "FAILED"


class EvidenceValidity(StrEnum):
    VALID = "VALID"
    INVALIDATED = "INVALIDATED"


class ProposalType(StrEnum):
    PROJECT_RESOLUTION = "PROJECT_RESOLUTION"
    REQUIREMENT_RECONCILIATION = "REQUIREMENT_RECONCILIATION"
    RETRACTION_CORRECTION = "RETRACTION_CORRECTION"


class PolicyDecision(StrEnum):
    ALLOW_AUTO_ACTION = "ALLOW_AUTO_ACTION"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    REJECT_PROPOSAL = "REJECT_PROPOSAL"


class TransitionDisposition(StrEnum):
    AUTO_APPLY = "AUTO_APPLY"
    BLOCK = "BLOCK"
    REVIEW = "REVIEW"


class TransitionStatus(StrEnum):
    PREVIEWED = "PREVIEWED"
    APPLIED = "APPLIED"
    REJECTED = "REJECTED"
    SUPERSEDED = "SUPERSEDED"


class ReviewStatus(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    CORRECTED = "CORRECTED"
    REJECTED = "REJECTED"


class ReviewType(StrEnum):
    PROJECT_RESOLUTION = "PROJECT_RESOLUTION"
    REQUIREMENT_CHANGE = "REQUIREMENT_CHANGE"
    NEW_REQUIREMENT = "NEW_REQUIREMENT"
    RETRACTION_CORRECTION = "RETRACTION_CORRECTION"
