import type {
  EvidenceLineage,
  ProjectActivityEvent,
  ProjectSummary,
  ProjectWorkspace,
} from "../api/types";

export const previewProjects: ProjectSummary[] = [
  {
    id: "preview-project-104",
    project_code: "TW-104",
    name: "Release Control Platform",
    status: "ACTIVE",
    created_at: "2026-09-01T09:00:00Z",
    updated_at: "2026-10-04T08:00:00Z",
  },
  {
    id: "preview-project-221",
    project_code: "TW-221",
    name: "Data Migration Programme",
    status: "ACTIVE",
    created_at: "2026-09-12T09:00:00Z",
    updated_at: "2026-10-03T13:20:00Z",
  },
  {
    id: "preview-project-319",
    project_code: "TW-319",
    name: "Access Review Service",
    status: "CLOSED",
    created_at: "2026-08-18T09:00:00Z",
    updated_at: "2026-09-28T15:40:00Z",
  },
];

export const previewWorkspaces: Record<string, ProjectWorkspace> = {
  "preview-project-104": {
    project: previewProjects[0],
    contacts: [],
    identifiers: [
      {
        id: "preview-identifier-repo",
        identifier_type: "repository_url",
        display_value: "git.example.test/platform/release-control",
        verified: true,
      },
      {
        id: "preview-identifier-contract",
        identifier_type: "client_reference",
        display_value: "OPS-2026-104",
        verified: true,
      },
    ],
    requirements: [
      {
        id: "preview-req-security",
        name: "Security review",
        description: "Final security review and outstanding findings.",
        state: "PARTIAL",
        expected_date: "2026-10-12",
        created_at: "2026-09-02T09:00:00Z",
        updated_at: "2026-10-04T08:00:00Z",
      },
      {
        id: "preview-req-api-docs",
        name: "API documentation",
        description: "Reviewed endpoint and integration documentation.",
        state: "SATISFIED",
        expected_date: null,
        created_at: "2026-09-02T09:00:00Z",
        updated_at: "2026-10-02T11:00:00Z",
      },
      {
        id: "preview-req-access",
        name: "Access approval",
        description: "Approval for the production operator account.",
        state: "OPEN",
        expected_date: "2026-10-18",
        created_at: "2026-09-05T09:00:00Z",
        updated_at: "2026-09-05T09:00:00Z",
      },
      {
        id: "preview-req-compatibility",
        name: "Compatibility assessment",
        description: "Review remains unresolved pending a vendor response.",
        state: "REVIEW",
        expected_date: null,
        created_at: "2026-09-07T09:00:00Z",
        updated_at: "2026-10-01T14:00:00Z",
      },
    ],
  },
  "preview-project-221": {
    project: previewProjects[1],
    contacts: [],
    identifiers: [
      {
        id: "preview-identifier-migration",
        identifier_type: "external_project_id",
        display_value: "MIGRATION-221",
        verified: true,
      },
    ],
    requirements: [
      {
        id: "preview-req-mapping",
        name: "Field mapping",
        description: "Source and destination fields are mapped.",
        state: "SATISFIED",
        expected_date: null,
        created_at: "2026-09-13T09:00:00Z",
        updated_at: "2026-10-02T09:00:00Z",
      },
      {
        id: "preview-req-validation",
        name: "Data validation",
        description: "Validation results are being reviewed.",
        state: "PARTIAL",
        expected_date: "2026-10-15",
        created_at: "2026-09-13T09:00:00Z",
        updated_at: "2026-10-03T13:20:00Z",
      },
    ],
  },
  "preview-project-319": {
    project: previewProjects[2],
    contacts: [],
    identifiers: [],
    requirements: [],
  },
};

export const previewActivity: Record<string, ProjectActivityEvent[]> = {
  "preview-project-104": [
    {
      event_id: "preview-event-security",
      event_type: "REQUIREMENT_CHANGE_APPLIED",
      occurred_at: "2026-10-04T08:00:00Z",
      project_id: "preview-project-104",
      correspondence_event_id: "preview-correspondence-security",
      requirement_id: "preview-req-security",
      summary: 'Requirement "Security review" moved OPEN to PARTIAL',
      attribution: "AUTOMATIC",
      authenticated_operator_subject: null,
      operator_supplied_actor_label: null,
      proposal_id: "preview-proposal-security",
      policy_evaluation_id: "preview-policy-security",
      state_transition_id: "preview-transition-security",
      review_item_id: null,
    },
    {
      event_id: "preview-event-docs",
      event_type: "REQUIREMENT_CHANGE_APPLIED",
      occurred_at: "2026-10-02T11:00:00Z",
      project_id: "preview-project-104",
      correspondence_event_id: "preview-correspondence-docs",
      requirement_id: "preview-req-api-docs",
      summary: 'Requirement "API documentation" moved OPEN to SATISFIED',
      attribution: "HUMAN",
      authenticated_operator_subject: "verified-operator-subject",
      operator_supplied_actor_label: null,
      proposal_id: "preview-proposal-docs",
      policy_evaluation_id: "preview-policy-docs",
      state_transition_id: "preview-transition-docs",
      review_item_id: null,
    },
    {
      event_id: "preview-event-linked",
      event_type: "CORRESPONDENCE_LINKED",
      occurred_at: "2026-10-01T09:00:00Z",
      project_id: "preview-project-104",
      correspondence_event_id: "preview-correspondence-linked",
      requirement_id: null,
      summary: "Correspondence linked to this project",
      attribution: "AUTOMATIC",
      authenticated_operator_subject: null,
      operator_supplied_actor_label: null,
      proposal_id: "preview-proposal-link",
      policy_evaluation_id: "preview-policy-link",
      state_transition_id: null,
      review_item_id: null,
    },
  ],
  "preview-project-221": [
    {
      event_id: "preview-event-validation",
      event_type: "REQUIREMENT_CHANGE_PROPOSED",
      occurred_at: "2026-10-03T13:20:00Z",
      project_id: "preview-project-221",
      correspondence_event_id: "preview-correspondence-validation",
      requirement_id: "preview-req-validation",
      summary: 'Requirement "Data validation" change sent for review',
      attribution: "NONE",
      authenticated_operator_subject: null,
      operator_supplied_actor_label: null,
      proposal_id: "preview-proposal-validation",
      policy_evaluation_id: "preview-policy-validation",
      state_transition_id: "preview-transition-validation",
      review_item_id: "preview-review-validation",
    },
  ],
  "preview-project-319": [],
};

export const previewLineage: EvidenceLineage = {
  completeness: "COMPLETE",
  completeness_notes: [],
  correspondence: {
    id: "preview-correspondence-security",
    source: "gmail",
    sender_identifier: "release-owner@example.test",
    subject: "Security review status",
    body: "The security assessment is attached. Two findings remain open.",
    received_at: "2026-10-04T07:40:00Z",
  },
  attachments: [
    {
      id: "preview-attachment-security",
      filename: "security-assessment.pdf",
      mime_type: "application/pdf",
      content_hash: null,
    },
  ],
  evidence: [
    {
      id: "preview-evidence-security",
      correspondence_event_id: "preview-correspondence-security",
      attachment_id: "preview-attachment-security",
      project_id: "preview-project-104",
      requirement_id: "preview-req-security",
      source_type: "ATTACHMENT_TEXT",
      excerpt: "The security assessment is complete. Two findings remain open.",
      start_offset: 0,
      end_offset: 66,
      page_number: 3,
      section: "Findings",
      validity_at_proposal: "VALID",
      validity_at_policy: "VALID",
      validity_at_outcome: "VALID",
      current_validity: "VALID",
      invalidated_at: null,
      invalidation_reason: null,
      linked_to_proposal: true,
      linked_to_policy: true,
      linked_to_transition: true,
    },
  ],
  proposal: {
    id: "preview-proposal-security",
    proposal_type: "REQUIREMENT_RECONCILIATION",
    model_identifier: "Configured model",
    prompt_version: "requirement-reconciler/1",
    input_hash: "preview-only",
    structured_output: { requirement_state: "PARTIAL" },
    created_at: "2026-10-04T07:45:00Z",
  },
  policy: {
    id: "preview-policy-security",
    policy_version: "requirement-policy/1",
    decision: "ALLOW_AUTO_ACTION",
    triggered_rule_ids: ["RID-300-OPEN-TO-PARTIAL", "RID-301-AUTO-ELIGIBLE"],
    reasons: ["Valid requirement-scoped evidence supports the proposed partial update."],
    evaluated_at: "2026-10-04T07:50:00Z",
  },
  transition: {
    id: "preview-transition-security",
    affected_entity_type: "REQUIREMENT_BUNDLE",
    affected_entity_id: "preview-proposal-security",
    historical_current_state: { requirement_state: "OPEN", expected_date: null },
    historical_proposed_state: { requirement_state: "PARTIAL", expected_date: "2026-10-12" },
    requirement_effects: [],
    disposition: "AUTO_APPLY",
    status: "APPLIED",
    created_at: "2026-10-04T07:50:00Z",
    applied_at: "2026-10-04T07:50:00Z",
  },
  review: null,
  audit_events: [],
  historical_outcome: {
    attribution: "AUTOMATIC",
    occurred_at: "2026-10-04T07:50:00Z",
    authenticated_operator_subject: null,
    operator_supplied_actor_label: null,
  },
  current_state: {
    linked_project_ids: ["preview-project-104"],
    requirements: [
      {
        requirement_id: "preview-req-security",
        exists: true,
        project_id: "preview-project-104",
        state: "PARTIAL",
        expected_date: "2026-10-12",
      },
    ],
  },
};
