"""create core domain schema

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-01 00:33:24.061952
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0002'
down_revision: str | Sequence[str] | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('correspondence_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('external_event_id', sa.String(), nullable=False),
    sa.Column('external_conversation_id', sa.String(), nullable=True),
    sa.Column('sender_identifier', sa.String(), nullable=False),
    sa.Column('sender_email', sa.String(), nullable=True),
    sa.Column('sender_name', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processing_state', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'RETRYABLE_FAILURE', 'TERMINAL_FAILURE', name='correspondence_processing_state', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('source_metadata', sa.JSON(), nullable=True),
    sa.Column('failure_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("btrim(external_event_id) <> ''", name='ck_correspondence_events_external_event_not_blank'),
    sa.CheckConstraint("btrim(sender_identifier) <> ''", name='ck_correspondence_events_sender_identifier_not_blank'),
    sa.CheckConstraint("btrim(source) <> ''", name='ck_correspondence_events_source_not_blank'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_event_id', name='uq_correspondence_events_source_external_event')
    )
    op.create_index('ix_correspondence_events_processing_received', 'correspondence_events', ['processing_state', 'received_at'], unique=False)
    op.create_index('ix_correspondence_events_source_conversation', 'correspondence_events', ['source', 'external_conversation_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('normalized_name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CLOSED', name='project_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("btrim(name) <> ''", name='ck_projects_name_not_blank'),
    sa.CheckConstraint("btrim(normalized_name) <> ''", name='ck_projects_normalized_name_not_blank'),
    sa.CheckConstraint("btrim(project_code) <> ''", name='ck_projects_code_not_blank'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_code', name='uq_projects_project_code')
    )
    op.create_index('ix_projects_normalized_name', 'projects', ['normalized_name'], unique=False)
    op.create_table('ai_proposals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('correspondence_event_id', sa.Uuid(), nullable=False),
    sa.Column('proposal_type', sa.Enum('PROJECT_RESOLUTION', 'REQUIREMENT_RECONCILIATION', 'RETRACTION_CORRECTION', name='proposal_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('model_identifier', sa.String(), nullable=False),
    sa.Column('prompt_version', sa.String(), nullable=False),
    sa.Column('input_hash', sa.String(), nullable=False),
    sa.Column('input_metadata', sa.JSON(), nullable=True),
    sa.Column('structured_output', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("btrim(input_hash) <> ''", name='ck_ai_proposals_input_hash_not_blank'),
    sa.CheckConstraint("btrim(model_identifier) <> ''", name='ck_ai_proposals_model_identifier_not_blank'),
    sa.CheckConstraint("btrim(prompt_version) <> ''", name='ck_ai_proposals_prompt_version_not_blank'),
    sa.ForeignKeyConstraint(['correspondence_event_id'], ['correspondence_events.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_proposals_event_type', 'ai_proposals', ['correspondence_event_id', 'proposal_type'], unique=False)
    op.create_table('attachments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('correspondence_event_id', sa.Uuid(), nullable=False),
    sa.Column('source_attachment_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('extraction_metadata', sa.JSON(), nullable=True),
    sa.Column('parsed_metadata', sa.JSON(), nullable=True),
    sa.Column('processing_state', sa.Enum('PENDING', 'EXTRACTED', 'FALLBACK_REQUIRED', 'UNSUPPORTED', 'FAILED', name='attachment_processing_state', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("btrim(filename) <> ''", name='ck_attachments_filename_not_blank'),
    sa.CheckConstraint("btrim(mime_type) <> ''", name='ck_attachments_mime_type_not_blank'),
    sa.CheckConstraint("btrim(source_attachment_id) <> ''", name='ck_attachments_source_id_not_blank'),
    sa.CheckConstraint('size_bytes >= 0', name='ck_attachments_size_nonnegative'),
    sa.ForeignKeyConstraint(['correspondence_event_id'], ['correspondence_events.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correspondence_event_id', 'source_attachment_id', name='uq_attachments_event_source_attachment')
    )
    op.create_index('ix_attachments_correspondence_event_id', 'attachments', ['correspondence_event_id'], unique=False)
    op.create_index('ix_attachments_processing_state', 'attachments', ['processing_state'], unique=False)
    op.create_table('correspondence_project_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('correspondence_event_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['correspondence_event_id'], ['correspondence_events.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correspondence_event_id', 'project_id', name='uq_correspondence_project_links_event_project')
    )
    op.create_index('ix_correspondence_project_links_project_id', 'correspondence_project_links', ['project_id'], unique=False)
    op.create_table('project_contacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('email_normalized', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("btrim(display_name) <> ''", name='ck_project_contacts_name_not_blank'),
    sa.CheckConstraint("btrim(email_normalized) <> ''", name='ck_project_contacts_email_not_blank'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'email_normalized', name='uq_project_contacts_project_email')
    )
    op.create_index('ix_project_contacts_email_normalized', 'project_contacts', ['email_normalized'], unique=False)
    op.create_table('project_identifiers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('identifier_type', sa.String(), nullable=False),
    sa.Column('display_value', sa.String(), nullable=False),
    sa.Column('normalized_value', sa.String(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("btrim(display_value) <> ''", name='ck_project_identifiers_display_value_not_blank'),
    sa.CheckConstraint("btrim(identifier_type) <> ''", name='ck_project_identifiers_type_not_blank'),
    sa.CheckConstraint("btrim(normalized_value) <> ''", name='ck_project_identifiers_normalized_value_not_blank'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'identifier_type', 'normalized_value', name='uq_project_identifiers_project_type_value')
    )
    op.create_index('ix_project_identifiers_type_normalized_value', 'project_identifiers', ['identifier_type', 'normalized_value'], unique=False)
    op.create_table('requirements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('state', sa.Enum('OPEN', 'PARTIAL', 'SATISFIED', 'REVIEW', name='requirement_state', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("btrim(name) <> ''", name='ck_requirements_name_not_blank'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_requirements_project_id', 'requirements', ['project_id'], unique=False)
    op.create_table('evidence_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('correspondence_event_id', sa.Uuid(), nullable=False),
    sa.Column('attachment_id', sa.Uuid(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('requirement_id', sa.Uuid(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('normalized_value', sa.String(), nullable=True),
    sa.Column('provenance_metadata', sa.JSON(), nullable=True),
    sa.Column('validity', sa.Enum('VALID', 'INVALIDATED', name='evidence_validity', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('invalidated_by_correspondence_event_id', sa.Uuid(), nullable=True),
    sa.Column('invalidation_reason', sa.Text(), nullable=True),
    sa.Column('invalidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(validity = 'VALID' AND invalidated_by_correspondence_event_id IS NULL AND invalidation_reason IS NULL AND invalidated_at IS NULL) OR (validity = 'INVALIDATED' AND invalidated_by_correspondence_event_id IS NOT NULL AND btrim(invalidation_reason) <> '' AND invalidated_at IS NOT NULL)", name='ck_evidence_items_invalidation_complete'),
    sa.CheckConstraint("btrim(excerpt) <> ''", name='ck_evidence_items_excerpt_not_blank'),
    sa.CheckConstraint("btrim(source_type) <> ''", name='ck_evidence_items_source_type_not_blank'),
    sa.CheckConstraint('page_number IS NULL OR page_number >= 1', name='ck_evidence_items_page_number_positive'),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['correspondence_event_id'], ['correspondence_events.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['invalidated_by_correspondence_event_id'], ['correspondence_events.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evidence_items_attachment_id', 'evidence_items', ['attachment_id'], unique=False)
    op.create_index('ix_evidence_items_correspondence_event_id', 'evidence_items', ['correspondence_event_id'], unique=False)
    op.create_index('ix_evidence_items_project_id', 'evidence_items', ['project_id'], unique=False)
    op.create_index('ix_evidence_items_requirement_validity', 'evidence_items', ['requirement_id', 'validity'], unique=False)
    op.create_table('policy_evaluations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ai_proposal_id', sa.Uuid(), nullable=False),
    sa.Column('policy_version', sa.String(), nullable=False),
    sa.Column('decision', sa.Enum('ALLOW_AUTO_ACTION', 'REVIEW_REQUIRED', 'REJECT_PROPOSAL', name='policy_decision', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('triggered_rule_ids', sa.JSON(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("btrim(policy_version) <> ''", name='ck_policy_evaluations_version_not_blank'),
    sa.ForeignKeyConstraint(['ai_proposal_id'], ['ai_proposals.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ai_proposal_id', 'policy_version', name='uq_policy_evaluations_proposal_version')
    )
    op.create_index('ix_policy_evaluations_decision', 'policy_evaluations', ['decision'], unique=False)
    op.create_table('ai_proposal_evidence',
    sa.Column('ai_proposal_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_item_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['ai_proposal_id'], ['ai_proposals.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['evidence_item_id'], ['evidence_items.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ai_proposal_id', 'evidence_item_id', name='pk_ai_proposal_evidence')
    )
    op.create_index('ix_ai_proposal_evidence_evidence_item_id', 'ai_proposal_evidence', ['evidence_item_id'], unique=False)
    op.create_table('policy_evaluation_evidence',
    sa.Column('policy_evaluation_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_item_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_item_id'], ['evidence_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['policy_evaluation_id'], ['policy_evaluations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('policy_evaluation_id', 'evidence_item_id', name='pk_policy_evaluation_evidence')
    )
    op.create_index('ix_policy_evaluation_evidence_evidence_item_id', 'policy_evaluation_evidence', ['evidence_item_id'], unique=False)
    op.create_table('state_transitions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ai_proposal_id', sa.Uuid(), nullable=False),
    sa.Column('policy_evaluation_id', sa.Uuid(), nullable=False),
    sa.Column('affected_entity_type', sa.String(), nullable=False),
    sa.Column('affected_entity_id', sa.Uuid(), nullable=False),
    sa.Column('current_state', sa.JSON(), nullable=False),
    sa.Column('proposed_state', sa.JSON(), nullable=False),
    sa.Column('requirement_effects', sa.JSON(), nullable=False),
    sa.Column('document_effects', sa.JSON(), nullable=False),
    sa.Column('follow_up_effects', sa.JSON(), nullable=False),
    sa.Column('disposition', sa.Enum('AUTO_APPLY', 'BLOCK', 'REVIEW', name='transition_disposition', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('PREVIEWED', 'APPLIED', 'REJECTED', 'SUPERSEDED', name='transition_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'APPLIED' AND applied_at IS NOT NULL) OR (status <> 'APPLIED' AND applied_at IS NULL)", name='ck_state_transitions_applied_at_matches_status'),
    sa.CheckConstraint("btrim(affected_entity_type) <> ''", name='ck_state_transitions_entity_type_not_blank'),
    sa.ForeignKeyConstraint(['ai_proposal_id'], ['ai_proposals.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['policy_evaluation_id'], ['policy_evaluations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_evaluation_id', 'affected_entity_type', 'affected_entity_id', name='uq_state_transitions_policy_entity')
    )
    op.create_index('ix_state_transitions_affected_entity', 'state_transitions', ['affected_entity_type', 'affected_entity_id'], unique=False)
    op.create_index('ix_state_transitions_status', 'state_transitions', ['status'], unique=False)
    op.create_table('review_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('correspondence_event_id', sa.Uuid(), nullable=False),
    sa.Column('state_transition_id', sa.Uuid(), nullable=False),
    sa.Column('review_type', sa.Enum('PROJECT_RESOLUTION', 'REQUIREMENT_CHANGE', 'NEW_REQUIREMENT', 'RETRACTION_CORRECTION', name='review_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('review_reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'CORRECTED', 'REJECTED', name='review_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('correction_payload', sa.JSON(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'PENDING' AND resolved_at IS NULL AND correction_payload IS NULL) OR (status = 'CORRECTED' AND resolved_at IS NOT NULL AND correction_payload IS NOT NULL) OR (status IN ('APPROVED', 'REJECTED') AND resolved_at IS NOT NULL AND correction_payload IS NULL)", name='ck_review_items_resolution_matches_status'),
    sa.CheckConstraint("btrim(review_reason) <> ''", name='ck_review_items_reason_not_blank'),
    sa.ForeignKeyConstraint(['correspondence_event_id'], ['correspondence_events.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['state_transition_id'], ['state_transitions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state_transition_id', name='uq_review_items_state_transition_id')
    )
    op.create_index('ix_review_items_correspondence_event_id', 'review_items', ['correspondence_event_id'], unique=False)
    op.create_index('ix_review_items_status_created', 'review_items', ['status', 'created_at'], unique=False)
    op.create_table('state_transition_evidence',
    sa.Column('state_transition_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_item_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_item_id'], ['evidence_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['state_transition_id'], ['state_transitions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('state_transition_id', 'evidence_item_id', name='pk_state_transition_evidence')
    )
    op.create_index('ix_state_transition_evidence_evidence_item_id', 'state_transition_evidence', ['evidence_item_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('actor_type', sa.String(), nullable=False),
    sa.Column('actor_identifier', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('correspondence_event_id', sa.Uuid(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('requirement_id', sa.Uuid(), nullable=True),
    sa.Column('ai_proposal_id', sa.Uuid(), nullable=True),
    sa.Column('policy_evaluation_id', sa.Uuid(), nullable=True),
    sa.Column('state_transition_id', sa.Uuid(), nullable=True),
    sa.Column('review_item_id', sa.Uuid(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("btrim(actor_type) <> ''", name='ck_audit_events_actor_type_not_blank'),
    sa.CheckConstraint("btrim(event_type) <> ''", name='ck_audit_events_event_type_not_blank'),
    sa.CheckConstraint('correspondence_event_id IS NOT NULL OR project_id IS NOT NULL OR requirement_id IS NOT NULL OR ai_proposal_id IS NOT NULL OR policy_evaluation_id IS NOT NULL OR state_transition_id IS NOT NULL OR review_item_id IS NOT NULL', name='ck_audit_events_has_lineage'),
    sa.ForeignKeyConstraint(['ai_proposal_id'], ['ai_proposals.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['correspondence_event_id'], ['correspondence_events.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['policy_evaluation_id'], ['policy_evaluations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['review_item_id'], ['review_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['state_transition_id'], ['state_transitions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_events_correspondence_event_id', 'audit_events', ['correspondence_event_id'], unique=False)
    op.create_index('ix_audit_events_project_occurred', 'audit_events', ['project_id', 'occurred_at'], unique=False)
    op.create_index('ix_audit_events_transition_id', 'audit_events', ['state_transition_id'], unique=False)
    op.create_index('ix_audit_events_type_occurred', 'audit_events', ['event_type', 'occurred_at'], unique=False)
    op.create_table('review_item_candidate_projects',
    sa.Column('review_item_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['review_item_id'], ['review_items.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('review_item_id', 'project_id', name='pk_review_item_candidate_projects')
    )
    op.create_index('ix_review_item_candidate_projects_project_id', 'review_item_candidate_projects', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_review_item_candidate_projects_project_id', table_name='review_item_candidate_projects')
    op.drop_table('review_item_candidate_projects')
    op.drop_index('ix_audit_events_type_occurred', table_name='audit_events')
    op.drop_index('ix_audit_events_transition_id', table_name='audit_events')
    op.drop_index('ix_audit_events_project_occurred', table_name='audit_events')
    op.drop_index('ix_audit_events_correspondence_event_id', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index('ix_state_transition_evidence_evidence_item_id', table_name='state_transition_evidence')
    op.drop_table('state_transition_evidence')
    op.drop_index('ix_review_items_status_created', table_name='review_items')
    op.drop_index('ix_review_items_correspondence_event_id', table_name='review_items')
    op.drop_table('review_items')
    op.drop_index('ix_state_transitions_status', table_name='state_transitions')
    op.drop_index('ix_state_transitions_affected_entity', table_name='state_transitions')
    op.drop_table('state_transitions')
    op.drop_index('ix_policy_evaluation_evidence_evidence_item_id', table_name='policy_evaluation_evidence')
    op.drop_table('policy_evaluation_evidence')
    op.drop_index('ix_ai_proposal_evidence_evidence_item_id', table_name='ai_proposal_evidence')
    op.drop_table('ai_proposal_evidence')
    op.drop_index('ix_policy_evaluations_decision', table_name='policy_evaluations')
    op.drop_table('policy_evaluations')
    op.drop_index('ix_evidence_items_requirement_validity', table_name='evidence_items')
    op.drop_index('ix_evidence_items_project_id', table_name='evidence_items')
    op.drop_index('ix_evidence_items_correspondence_event_id', table_name='evidence_items')
    op.drop_index('ix_evidence_items_attachment_id', table_name='evidence_items')
    op.drop_table('evidence_items')
    op.drop_index('ix_requirements_project_id', table_name='requirements')
    op.drop_table('requirements')
    op.drop_index('ix_project_identifiers_type_normalized_value', table_name='project_identifiers')
    op.drop_table('project_identifiers')
    op.drop_index('ix_project_contacts_email_normalized', table_name='project_contacts')
    op.drop_table('project_contacts')
    op.drop_index('ix_correspondence_project_links_project_id', table_name='correspondence_project_links')
    op.drop_table('correspondence_project_links')
    op.drop_index('ix_attachments_processing_state', table_name='attachments')
    op.drop_index('ix_attachments_correspondence_event_id', table_name='attachments')
    op.drop_table('attachments')
    op.drop_index('ix_ai_proposals_event_type', table_name='ai_proposals')
    op.drop_table('ai_proposals')
    op.drop_index('ix_projects_normalized_name', table_name='projects')
    op.drop_table('projects')
    op.drop_index('ix_correspondence_events_source_conversation', table_name='correspondence_events')
    op.drop_index('ix_correspondence_events_processing_received', table_name='correspondence_events')
    op.drop_table('correspondence_events')
    # ### end Alembic commands ###
